# Generated by Django 4.0.10 on 2023-05-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
